sudo: required

language: go

go:
  - 1.9

services:
  - docker

env:
  global:
    - TRAVIS=1
    - DB_PASSWORD=secret
    - DB_DATABASE=test
    - MYSQL_PORT=19423
    - MYSQL_ADDR=root:${DB_PASSWORD}@(127.0.0.1:${MYSQL_PORT})/${DB_DATABASE}

before_install:
  - go get -u ./...
  - go get -u github.com/UnnoTed/fileb0x
  - go get -u golang.org/x/tools/cmd/goimports
  - go generate ./gen/...
  - go install ./cmd/orm
  - go generate ./example/...
  - go get -t ./...
  - ./scripts/start-mysql.sh

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
