language: go
sudo: false
go:
  - 1.9

before_install:
  - go get -u -t ./...
  - go get -u github.com/UnnoTed/fileb0x

script:
  - ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
